name: CI Pipeline for Django and Node.js

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-django:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]  # Testando em múltiplas versões de Python
    steps:
      # Step 1: Fazer checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configurar o ambiente Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Step 3: Instalar dependências do Python
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Certifique-se de que o arquivo está na raiz do projeto

      # Step 4: Executar testes do Django
      - name: Run Django tests
        run: python manage.py test
